version: "3.9"
services:
  mysql1:
    image: mysql:latest
    container_name: db1
    ports:
      - "3306:3306" 
    environment:  
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - ./mysql_data:/var/lib/mysql  